# Generated by Django 3.2.6 on 2021-08-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
