# Generated by Django 3.2.6 on 2021-08-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
