# Generated by Django 3.2.6 on 2021-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210817_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='static/items/foto/no_foto.jpg', upload_to='static/items/foto'),
        ),
    ]
