# Generated by Django 3.2.6 on 2021-08-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_promotion_promotionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_items',
        ),
        migrations.AddField(
            model_name='promotionitem',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.promotion'),
        ),
    ]
