# Generated by Django 3.2.6 on 2021-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20210817_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
