# Generated by Django 3.2.6 on 2021-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210817_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discont',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
