# Generated by Django 3.2.6 on 2021-09-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_discont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discont',
            new_name='discount',
        ),
    ]
